config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources 'flats'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      @flat.save
      redirect_to(flat_path(@flat))
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <%= simple_form_for(flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="spacer"></div>

<h1 class="mx-3">Flats List</h1>

<div class="spacer"></div>

<div class="container">
  <% @flats.each do |r| %>
    <%= link_to flat_path(r) do %>
      <div class="card m-3">
        <h4 class="m-3"><%= r.name %></h4>
        <h6 class="mx-3"><%= r.address %></h6>
        <p class="mx-3" style="text-align: right;"><%= r.price_per_night %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<div class="spacer"></div>

<div class="container">
  <div class="card">
    <h2><%= @flat.name %></h2>
    <h3><%= @flat.address %></h3>
    <p><%= @flat.description %></p>
    <p>$<%= @flat.price_per_night %>/per night</p>
    <p><%= @flat.number_of_guests %> guests total</p>
  </div>
</div>

<%# link_to "Add Review", new_flat_review_path(@flat), class: "btn btn-primary m-3" %>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Rails Yelp</a>
      <%= link_to "Flats List", flats_path, class: "ml-5" %>
      <%= link_to "Add New Flat", new_flat_path, class: "ml-5" %>
    </nav>

    <%= yield %>
  </body>
</html>